apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "vineetpod"
  annotations:
    "humanitec.com/orgId": "flo24-platform-engineering-bootcamp"
    "humanitec.com/appId": "vineetpod"
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
